name: "terraform apply pr comment"

on:
  issue_comment:

defaults:
  run:
    working-directory: terraform/env/dev

jobs:
  terraform_apply:
    name: "terraform apply pr comment"
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '.deploy' }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: "Get branch name and sha"
        id: get_branch
        run: |
          PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
          echo "::set-output name=branch::$(echo $PR | jq -r '.head.ref')"
          echo "::set-output name=sha::$(echo $PR | jq -r '.head.sha')"

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_branch.outputs.branch }}
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `start terraform apply....
            CI URL: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}
            `
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -var-file dev.auto.tfvars
        env:
          TF_VAR_mysql_password: ${{ secrets.TF_VAR_mysql_password }}
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -auto-approve -var-file dev.auto.tfvars
        env:
          TF_VAR_mysql_password: ${{ secrets.TF_VAR_mysql_password }}
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        env:
          APPLY: ${{ steps.apply.outputs.stdout }}
          APPLY_ERROR: ${{ steps.apply.outputs.stderr }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### .deploy „ÅÆÁµêÊûú„ÇíË°®Á§∫„Åô„Çã„ÄÇ
            #### Terraform apply üìñ\`${{ steps.apply.outcome }}\`

            <details><summary>Show Apply Result</summary>

            \`\`\`terraform
            ${process.env.APPLY}
            \`\`\`

            </details>
            
            ${ process.env.APPLY_ERROR &&
              `<details><summary>Error</summary>

              \`\`\`terraform
              ${process.env.APPLY_ERROR}
              \`\`\`

              </details>
            `}`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1